# Generated by Django 3.2.5 on 2024-01-21 17:22

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('project_name', models.CharField(max_length=250)),
                ('project_sort_desc', models.CharField(max_length=255)),
                ('project_desc', models.TextField()),
                ('project_link', models.CharField(max_length=150)),
                ('project_downlod_able', models.BooleanField(default=False)),
                ('project_image', models.ImageField(blank=True, null=True, unique=True, upload_to=projects.models.modify_upload_file_name)),
                ('project_file', models.FileField(blank=True, null=True, upload_to=projects.models.modify_project_files)),
            ],
        ),
    ]
