# Generated by Django 3.2.5 on 2024-01-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email_to', models.CharField(max_length=255)),
                ('email_subject', models.CharField(max_length=255)),
                ('email_template', models.CharField(max_length=255)),
                ('email_for', models.CharField(choices=[('new_contact', 'New contact'), ('new_post', 'New Post'), ('new_subscription', 'New subscription')], max_length=255)),
                ('email_status', models.CharField(choices=[('0', 'Not send'), ('1', 'Send')], max_length=255)),
                ('ref_id', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'email_queue',
                'db_table': 'email_queue',
            },
        ),
    ]
