# Generated by Django 3.2.5 on 2024-05-13 01:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_users', '0003_auto_20240425_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUserLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('ipaddress', models.CharField(max_length=255)),
                ('is_login', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('login_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='site_users.siteuser')),
            ],
            options={
                'verbose_name': 'site user auth',
                'db_table': 'site_user_auth',
            },
        ),
    ]
