# Generated by Django 3.2.5 on 2024-04-25 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={'verbose_name': 'site user'},
        ),
    ]
