# Generated by Django 3.2.5 on 2024-04-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_users', '0002_alter_siteuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
