# Generated by Django 5.1.1 on 2024-10-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_users', '0003_auto_20240425_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
