# Generated by Django 3.2.5 on 2024-01-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_response', models.CharField(choices=[('1', 'Responsed'), ('0', 'Not Responsed')], default='0', max_length=255)),
            ],
            options={
                'verbose_name': 'contact',
                'db_table': 'contact',
            },
        ),
    ]
