# Generated by Django 3.2.5 on 2024-01-21 17:22

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_sort_desc', models.TextField()),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to=blog.models.modify_upload_file_name)),
                ('blog_content', models.TextField()),
                ('blog_sl_no', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publish_status', models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], default='0', max_length=255)),
            ],
        ),
    ]
