# Generated by Django 5.0.7 on 2024-09-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_id',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
