# Generated by Django 5.0.7 on 2024-09-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_about_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
