# Generated by Django 5.1.1 on 2024-10-19 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_about_content_alter_about_about_id'),
        ('site_users', '0004_siteuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='site_users.siteuser'),
        ),
    ]
