# Generated by Django 3.2.5 on 2024-01-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('work_start', models.DateField()),
                ('work_end', models.DateField()),
                ('is_continue', models.BooleanField(default=True)),
                ('what_to_do', models.TextField()),
            ],
            options={
                'verbose_name': 'experience',
                'db_table': 'experience',
            },
        ),
    ]
