# Generated by Django 5.0.7 on 2024-09-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_icon_name', models.CharField(max_length=100)),
                ('skill_rating', models.IntegerField(default=5)),
                ('skill_sequance', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'skills',
                'db_table': 'skills',
            },
        ),
    ]
