# Generated by Django 5.0.7 on 2024-09-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'skill'},
        ),
        migrations.AlterModelTable(
            name='skill',
            table='skill',
        ),
    ]
